project:
  type: website

website:
  title: "ISSS26 Geospatial Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1"
        href: Hands-on_Ex/Hands_on_Ex01/Hands_on_Ex01/Hands-on_Ex01.html
      - text: "Hands-on Exercise 2"
        href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
      
     
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_Ex1.html
      - text: "In-class Exercise 4"
        href: In_class_Ex/In-class_Ex04/In-class_Ex04.html
      - text: "In-class Exercise 5"
        href: In_class_Ex/In-class_Ex05/In-class_Ex05.html
      - text: "In-class Exercise 5"
        href: In_class_Ex/In-class_Ex07/In-class_Ex07.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Ex/Take-home_Ex1/Take_home_Ex1.html
      - text: "Take-home Exercise 2"
        href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html
      - text: "Take-home Exercise 3"
        href: Take-home_Ex/Take-home_Ex3/Take-home_Ex3.html
 
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

