project:
  type: website

website:
  title: "ISSS26 Geospatial Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1"
        href: Hands_on_Ex/Hands_on_Ex01/Hands-on_Ex01.html
      - text: "Hands-on Exercise 1 Part 2"
        href: Hands_on_Ex/Hands_on_Ex01/Hands_on_Ex01b.html
      - text: "Hands-on Exercise 2"
        href: Hands_on_Ex/Hands_on_Ex02/Hands_on_Ex02.html
      - text: "Hands-on Exercise 2 Part 2"
        href: Hands_on_Ex/Hands_on_Ex02/Hands_on_Ex02b.html
      - text: "Hands-on Exercise 3"
        href: Hands_on_Ex/Hands_on_Ex03/Hands_on_Ex03.html
       
       
     
    - text: "In-Class Exercise"
      menu:
      - text: "In-Class Exercise 3a"
        href: In_Class_Ex/In_class_Ex03/In-class_Ex03a.html
      
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Ex/Take-home_Ex1/Take_home_Ex1.html
      - text: "Take-home Exercise 2"
        href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html
      - text: "Take-home Exercise 3"
        href: Take-home_Ex/Take-home_Ex3/Take-home_Ex3.html
 
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

