{
  "hash": "309a3d3f8969affaf2d019a64aef958e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 1: Hotspots on the Go: Clustering of Food Kiosks Across Singapore, 2024–Jun 2025\"\nauthor: \"Pwint Phoo Thaw\"\ndate: \"September 12, 2025\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n\n# **Problem Statement**\n\nFrom **Jan 2024 to Jun 2025**, Singapore saw rapid growth of **food kiosks (SSIC 56123)**—small, takeaway-focused outlets with little or no seating. Their expansion around **MRT nodes, malls, schools, offices, and HDB towns** can reshape micro-retail patterns, affect pedestrian space and curb logistics, and create pockets of under- or over-supply. This study uses ACRA registrations to reveal **where** and **when** kiosks emerge, how strongly they **cluster**, how activity **evolves over time**, and how locations relate to key **urban infrastructure**, to inform **evidence-based retail and land-use planning** in Singapore.\n\n## **1. Objectives**\n\n-   **Map Spatio-Temporal Distribution**\\\n    Track when and where new 56123 kiosks entered (2024–Jun 2025) and highlight hotspot areas by month and subzone.\n-   **Assess Clustering \\***\\\n    Use spatial statistics (KDE, Ripley’s K/L or O-ring) to test whether kiosks are clustered or dispersed and at what spatial scales.\n-   **Identify Temporal Waves**\\\n    Apply spatio-temporal KDE (STKDE) to reveal waves of kiosk entry (e.g., CBD/malls first, then diffusion to heartlands).\n-   **Examine Infrastructure Proximity \\***\\\n    Test whether kiosks concentrate near **MRT stations, malls, and schools** (buffer analysis; simple statistical tests).\n-   **Derive Planning Insights**\\\n    Translate findings into implications for **zoning/tenant-mix**, **transit-oriented clustering management**, curb/logistics planning, and **SME support**.\n\n## **2. Data Wrangling**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(readr, dplyr, tidyr, stringr, lubridate,terra,spatstat,\n               sf, tmap, units, httr, jsonlite, tidyverse,rvest )\n```\n:::\n\n\n\n### **2.1 Importing ACRA Data (Aspatial)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfolder_path <- \"data/aspatial/acra\"\nfile_list <- list.files(path=folder_path,\n                        pattern = \"^ACRA*.*\\\\.csv$\",\n                        full.names = TRUE)\n\nacra_data <- file_list %>%\n  map_dfr(read_csv)\n```\n:::\n\n\n\n**Saving ACRA data**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(acra_data,\n          \"data/rds/acra_data.rds\") \n```\n:::\n\n\n\n**Tidying ACRA data (56123 is for bubble tea shops)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### select target businesess, derive year, tidy postal code for geo coding and...\nbiz_56123 <- acra_data %>%\n  select(1:24) %>%\n  filter(primary_ssic_code == 56123) %>%\n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         YEAR = year(date),\n         MONTH_NUM = month(date),\n         MONTH_ABBR = month(date, label = TRUE, abbr = TRUE)) %>%\n  mutate(postal_code = str_pad(postal_code, width = 6, side = \"left\", pad = \"0\")) %>%\n   filter((YEAR == 2024 & MONTH_NUM >= 1) | (YEAR == 2025 & MONTH_NUM <= 6))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#|eval:false\n#|echo:false\nwrite_rds(biz_56123,\n\"data/rds/biz_56123.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_56123 <-\nread_rds(\"data/rds/biz_56123.rds\")\n```\n:::\n\n\n\n**Geocoding (for finding X,Y coordinates)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes <- unique(biz_56123$postal_code)\n\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"  ##API without paying\n\nfound <- data.frame()\nnot_found <- data.frame(postcode = character())\n\nfor (pc in postcodes) {\n  query <- list(\n    searchVal = pc,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum = \"1\"\n  )\n\n\n###converting to data frame\nres <- GET(url, query = query)\njson <- content(res)\n\nif (json$found != 0) {\n  df <- as.data.frame(json$results, stringsAsFactors = FALSE)\n  df$input_postcode <- pc\n  found <- bind_rows(found, df)\n  } else {\n  not_found <- bind_rows(not_found, data.frame(postcode = pc))\n  }\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfound <- found %>%\n  select(1:10)\n```\n:::\n\n\n\nAppending the location information (join it back with 56123 right one with new geo_coded postal_code\n\n2 columns in meter, 2 columns in Lon and Lat\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_56123_join = biz_56123 %>%\n   left_join(found,\n             by = c('postal_code' = 'POSTAL'))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(biz_56123_join, \"data/rds/biz_56123_join.rds\")\n```\n:::\n\n\n\n**Converting into SF data frame**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_56123_sf <- st_as_sf(biz_56123_join, \n                         coords = c(\"X\",\"Y\"),\n                         crs=3414) \nclass(biz_56123_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sf\"         \"tbl_df\"     \"tbl\"        \"data.frame\"\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(st_geometry(biz_56123_sf))\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# case-insensitive regex for trailing street-type words (and anything after them)\nsuffix_re <- \"(?i)\\\\s+(ROAD|RD|STREET|ST|AVENUE|AVE|DRIVE|DR|LANE|LN|CLOSE|CL|CRESCENT|CRES|TERRACE|TERR|WALK|PLACE|PL|PARK|PK|HEIGHTS|HTS|LINK|VIEW|WAY|COURT|CT|CIRCUIT|CIR|RISE|GROVE|GARDENS|GDN)(\\\\s+.*)?$\"\n\n# create Zone from street_name (fallback to STREET_NAME if needed)\nbiz_56123_sf <- biz_56123_sf %>%\n  mutate(\n    street_raw = coalesce(street_name),\n    Zone = street_raw %>%\n      str_replace_all(\"_\", \" \") %>%  # tidy underscores\n      str_squish() %>%               # trim extra spaces\n      str_remove(suffix_re) %>%      # drop trailing street-type\n      str_squish() %>%\n      str_to_upper()                 # <-- UPPER CASE\n  )\n\n# quick check\nbiz_56123_sf %>% select(street_raw, Zone) %>% head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 18595.32 ymin: 29312.14 xmax: 40699.29 ymax: 40086.81\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 6 × 3\n  street_raw            Zone                    geometry\n  <chr>                 <chr>                <POINT [m]>\n1 RAFFLES QUAY          RAFFLES QUAY (29958.79 29312.14)\n2 BUKIT BATOK STREET 21 BUKIT BATOK  (18595.32 36448.81)\n3 HOUGANG AVENUE 8      HOUGANG      (34784.67 40086.81)\n4 PAYA LEBAR ROAD       PAYA LEBAR    (34595.3 33453.44)\n5 BEDOK NORTH STREET 5  BEDOK NORTH  (40699.29 35436.94)\n6 ALJUNIED CRESCENT     ALJUNIED      (33884.7 33772.81)\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(biz_56123_sf, \"data/rds/biz_56123_sf.rds\")\n```\n:::\n\n\n\n### **2.2 Importing Geospatial Data**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_sf <- st_read(\"data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaKML.kml\") %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>% st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `URA_MP19_SUBZONE_NO_SEA_PL' from data source \n  `C:\\ppthaw2024\\ISSS626-Geospatial\\Take_Home_Ex\\Take_Home_Ex01\\data\\geospatial\\MasterPlan2019SubzoneBoundaryNoSeaKML.kml' \n  using driver `KML'\nSimple feature collection with 332 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_kml_field <- function(html_text, field_name) {\n  if (is.na(html_text) || html_text == \"\") return(NA_character_)\n  \n  page <- read_html(html_text)\n  rows <- page %>% html_elements(\"tr\")\n  \n  value <- rows %>%\n    keep(~ html_text2(html_element(.x, \"th\")) == field_name) %>%\n    html_element(\"td\") %>%\n    html_text2()\n  \n  if (length(value) == 0) NA_character_ else value\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_sf <- mpsz_sf %>%\n  mutate(\n    REGION_N = map_chr(Description, extract_kml_field, \"REGION_N\"),\n    PLN_AREA_N = map_chr(Description, extract_kml_field, \"PLN_AREA_N\"),\n    SUBZONE_N = map_chr(Description, extract_kml_field, \"SUBZONE_N\"),\n    SUBZONE_C = map_chr(Description, extract_kml_field, \"SUBZONE_C\")\n  ) %>%\n  select(-Name, -Description) %>%\n  relocate(geometry, .after = last_col())\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n###testing hands on 2.2\nmpsz_cl <- mpsz_sf %>%\n  filter(SUBZONE_N != \"SOUTHERN GROUP\",\n         PLN_AREA_N != \"WESTERN ISLANDS\",\n         PLN_AREA_N != \"NORTH-EASTERN ISLANDS\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mpsz_cl, \n          \"data/rds/mpsz_cl.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(mpsz_cl) == st_crs(biz_56123_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n#### **Mapping the geospatial data sets**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = mpsz_cl, fill = \"gray\", color = \"black\", size = 0.2) +\n  geom_sf(data = biz_56123_sf, color = \"black\", size = 1.2, alpha = 0.7) +\n  labs(title = \"Food Kiosks Across Singapore Subzones\",\n       subtitle = \"All layers aligned to EPSG:3414 (SVY21)\",\n       caption = \"Source: URA Master Plan & Data.gov.sg\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n### **2.3 Importing MRT Data**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt <- st_read(\"data/geospatial/LTAMRTStationExitKML.kml\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MRT_EXITS' from data source \n  `C:\\ppthaw2024\\ISSS626-Geospatial\\Take_Home_Ex\\Take_Home_Ex01\\data\\geospatial\\LTAMRTStationExitKML.kml' \n  using driver `KML'\nSimple feature collection with 563 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6368 ymin: 1.264972 xmax: 103.9893 ymax: 1.449157\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#|eval:false\n#|echo:false\nwrite_rds(mrt,\n\"data/rds/mrt.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt<-\nread_rds(\"data/rds/mrt.rds\")\n```\n:::\n\n\n\n#### **Mapping the geospatial data sets**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = mpsz_cl, fill = \"gray\", color = \"black\", size = 0.2) +\n  geom_sf(data = mrt, color = \"green\", size = 1.2, alpha = 0.7) +\n  labs(title = \"MRT Exit Across Singapore Subzones\",\n       subtitle = \"All layers aligned to EPSG:3414 (SVY21)\",\n       caption = \"Source: URA Master Plan & Data.gov.sg\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n### **2.4 Joining ARCA data and Geospatial data**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#####will do later\n```\n:::\n\n\n\n## **3 Objective: Clustering Analysis**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz_56123_ppp <- as.ppp(biz_56123_sf)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(biz_56123_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ppp\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(biz_56123_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  484 points\nAverage intensity 6.687421e-07 points per square unit\n\nCoordinates are given to 10 decimal places\n\nMark variables: uen, issuance_agency_id, entity_name, entity_type_description, \nbusiness_constitution_description, company_type_description, \npaf_constitution_description, entity_status_description, date, uen_issue_date, \naddress_type, block, street_name, level_no, unit_no, building_name, \npostal_code, other_address_line1, other_address_line2, account_due_date, \nannual_return_date, primary_ssic_code, primary_ssic_description, \nprimary_user_described_activity, YEAR, MONTH_NUM, MONTH_ABBR, SEARCHVAL, \nBLK_NO, ROAD_NAME, BUILDING, ADDRESS, LATITUDE, LONGITUDE, street_raw, Zone\nSummary:\n     uen            issuance_agency_id entity_name       \n Length:484         Length:484         Length:484        \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n                                                         \n entity_type_description business_constitution_description\n Length:484              Length:484                       \n Class :character        Class :character                 \n Mode  :character        Mode  :character                 \n                                                          \n                                                          \n                                                          \n                                                          \n company_type_description paf_constitution_description\n Length:484               Length:484                  \n Class :character         Class :character            \n Mode  :character         Mode  :character            \n                                                      \n                                                      \n                                                      \n                                                      \n entity_status_description      date            uen_issue_date      \n Length:484                Min.   :2024-01-01   Min.   :2024-01-01  \n Class :character          1st Qu.:2024-06-05   1st Qu.:2024-06-05  \n Mode  :character          Median :2024-11-13   Median :2024-11-13  \n                           Mean   :2024-10-30   Mean   :2024-10-30  \n                           3rd Qu.:2025-03-20   3rd Qu.:2025-03-20  \n                           Max.   :2025-06-30   Max.   :2025-06-30  \n                                                                    \n address_type          block           street_name          level_no        \n Length:484         Length:484         Length:484         Length:484        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   unit_no          building_name      postal_code        other_address_line1\n Length:484         Length:484         Length:484         Length:484         \n Class :character   Class :character   Class :character   Class :character   \n Mode  :character   Mode  :character   Mode  :character   Mode  :character   \n                                                                             \n                                                                             \n                                                                             \n                                                                             \n other_address_line2 account_due_date   annual_return_date primary_ssic_code\n Length:484          Length:484         Length:484         Min.   :56123    \n Class :character    Class :character   Class :character   1st Qu.:56123    \n Mode  :character    Mode  :character   Mode  :character   Median :56123    \n                                                           Mean   :56123    \n                                                           3rd Qu.:56123    \n                                                           Max.   :56123    \n                                                                            \n primary_ssic_description primary_user_described_activity      YEAR     \n Length:484               Length:484                      Min.   :2024  \n Class :character         Class :character                1st Qu.:2024  \n Mode  :character         Mode  :character                Median :2024  \n                                                          Mean   :2024  \n                                                          3rd Qu.:2025  \n                                                          Max.   :2025  \n                                                                        \n   MONTH_NUM        MONTH_ABBR   SEARCHVAL            BLK_NO         \n Min.   : 1.000   Apr    : 65   Length:484         Length:484        \n 1st Qu.: 3.000   Mar    : 63   Class :character   Class :character  \n Median : 5.000   May    : 58   Mode  :character   Mode  :character  \n Mean   : 5.411   Jun    : 55                                        \n 3rd Qu.: 8.000   Jan    : 50                                        \n Max.   :12.000   Feb    : 47                                        \n                  (Other):146                                        \n  ROAD_NAME           BUILDING           ADDRESS            LATITUDE        \n Length:484         Length:484         Length:484         Length:484        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  LONGITUDE          street_raw            Zone          \n Length:484         Length:484         Length:484        \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n                                                         \n\nWindow: rectangle = [12100.48, 47022.31] x [28677.01, 49401.78] units\n                    (34920 x 20720 units)\nWindow area = 723747000 square units\n```\n\n\n:::\n:::\n\n\n\n### **Creating *owin* object and combining point events**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsg_owin <- as.owin(mpsz_cl)\nclass(sg_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz56123_sg_ppp = biz_56123_ppp [sg_owin]\n```\n:::\n\n\n\n#### **3.1aClark-Evan Test without CSR for Nearest Neighbour Analysis**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(biz56123_sg_ppp,\n                correction=\"none\",\n                clipregion=\"sg_owin\",\n                alternative=c(\"clustered\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  biz56123_sg_ppp\nR = 0.51423, p-value < 2.2e-16\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n#### **Statistical conclusion**\n\n-   The test statistic **R = 0.514** (well **below 1**) and the **p-value \\< 2.2e-16**.\n\n    The food kioks locations are **much closer together than we’d expect by random chance**—i.e., they are **strongly clustered**, not evenly spread out.\n\n#### **3.1bClark-Evan Test with CSR for Nearest Neighbour Analysis**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(biz56123_sg_ppp,\n                correction=\"none\",\n                clipregion=\"sg_owin\",\n                alternative=c(\"clustered\"),\n                method=\"MonteCarlo\",\n                nsim=99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  biz56123_sg_ppp\nR = 0.51423, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n#### **Statistical conclusion**\n\n-   Clark–Evans NN test: **R = 0.514** (well below 1), **p \\< 2.2×10⁻¹⁶** → reject CSR; locations are **significantly clustered**.\n\n    Food kiosks are **much closer together** than random—i.e., **strongly clustered**, not evenly spread across Singapore.\n\n#### **3.2 Kernel Density Method**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiz56123sg_ppp_km <- rescale.ppp(biz56123_sg_ppp, 1000, \"km\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_biz56123_km <- density(biz56123sg_ppp_km,\n                              sigma=bw.diggle,\n                              edge=TRUE,\n                              kernel=\"gaussian\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(kde_biz56123_km)\n```\n\n::: {.cell-output-display}\n![](Take_Home_Ex01_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(kde_biz56123_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nreal-valued pixel image\n128 x 128 pixel array (ny, nx)\nenclosing rectangle: [2.667538, 55.94194] x [21.44847, 50.25633] km\ndimensions of each pixel: 0.416 x 0.2250614 km\nImage is defined on a subset of the rectangular grid\nSubset area = 669.941961122495 square km\nSubset area fraction = 0.437\nPixel values (inside window):\n\trange = [-1.109286e-14, 91.49934]\n\tintegral = 482.3433\n\tmean = 0.7199777\n```\n\n\n:::\n:::\n\n\n\n#### Statistical Takeaways\n\n-   The **integral ≈ 482.3** matches the number of kiosks → diagnostic check passed (KDE surface conserves counts).\n\n<!-- -->\n\n-    The **mean intensity ≈ 7.2×10⁻⁷ per m²** ≈ **0.72 kiosks per km²** on average over the study window—so most of Singapore is low-intensity with a few concentrated pockets.\n\n<!-- -->\n\n-   **Mean intensity:** **0.720 kiosks/km²** → the island-wide baseline is low; activity is concentrated in a few places.\n\n<!-- -->\n\n-    **Peak intensity:** **\\~91.5 kiosks/km²** → very small areas achieve extremely high density, confirming **tight hotspots**.\n\n-   Hotspots align with **MRT interchanges, mall corridors, CBD/town centres**; peripheral/industrial/green areas are cold.\n\n**Business Communications**\n\n-   **Retail gravity rules**: kiosks concentrate where **footfall and delivery access** are highest (CBD/malls/interchanges).\n\n<!-- -->\n\n-    **Saturation risk**: the same nodes show **over-concentration**—new kiosks here will face **tight competition and cannibalisation**.\n\n<!-- -->\n\n-    **Opportunity**: identify **underserved subzones** (low KDE but reasonable demand/transport) as candidate areas for **decentralised growth**.\n\n\n## **4 Objective: Examine Infrastructure Proximity**\n",
    "supporting": [
      "Take_Home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}